# SERVER
server:
  port: 3527
  servlet:
    context-path: "/"
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# Logging
logging:
  level:
    org.springframework: info
    org.springframework.web: debug



spring:
  # Profiles
  profiles:
    include: dev
  messages:
    encoding: UTF-8
    basename: messages/messages

jwt:
  secret: a2t1bHRyaXAtY2Fwc3RvbmUtZGVzaWduLXByb2plY3QtdGhyZWVnby1qd3Qtc2VjcmV0LWtleQ==
  exp: 30